Repository snuhcs-course/swpp-2023-project-team-2, pull requests merged in 2023-10, with the labels that each got.

#3 Feat/springboot api connection
  .firebaserc
  .github/workflows/firebase-hosting-merge.yml
  .github/workflows/firebase-hosting-pull-request.yml
  firebase.json
  public/404.html
  public/index.html
  springboot/.gitignore
  springboot/build.gradle.kts
  springboot/gradle/wrapper/gradle-wrapper.jar
  springboot/gradle/wrapper/gradle-wrapper.properties
  springboot/gradlew
  springboot/gradlew.bat
  springboot/settings.gradle.kts
  springboot/src/main/kotlin/com/goliath/emojihub/springboot/SpringbootApplication.kt
  springboot/src/main/kotlin/com/goliath/emojihub/springboot/config/FirebaseConfig.kt
  springboot/src/main/kotlin/com/goliath/emojihub/springboot/controller/UserController.kt
  springboot/src/main/kotlin/com/goliath/emojihub/springboot/dao/UserDao.kt
  springboot/src/main/kotlin/com/goliath/emojihub/springboot/model/User.kt
  springboot/src/main/kotlin/com/goliath/emojihub/springboot/service/UserService.kt
  springboot/src/main/kotlin/com/goliath/emojihub/springboot/service/UserServiceImpl.kt
  springboot/src/main/resources/application.properties
  springboot/src/test/kotlin/com/goliath/emojihub/springboot/SpringbootApplicationTests.kt
Labels: bug, enhancement

#7 fix: remove all firebase hosting related files
  .firebaserc
  .github/workflows/firebase-hosting-merge.yml
  .github/workflows/firebase-hosting-pull-request.yml
  firebase.json
  public/404.html
  public/index.html
Labels: bug

#6 Feat/back user api
  springboot/.gitignore
  springboot/build.gradle.kts
  springboot/src/main/kotlin/com/goliath/emojihub/springboot/common/Exceptions.kt
  springboot/src/main/kotlin/com/goliath/emojihub/springboot/config/FirebaseConfig.kt
  springboot/src/main/kotlin/com/goliath/emojihub/springboot/controller/UserController.kt
  springboot/src/main/kotlin/com/goliath/emojihub/springboot/dao/UserDao.kt
  springboot/src/main/kotlin/com/goliath/emojihub/springboot/dto/LoginRequest.kt
  springboot/src/main/kotlin/com/goliath/emojihub/springboot/dto/SignUpRequest.kt
  springboot/src/main/kotlin/com/goliath/emojihub/springboot/dto/UserDto.kt
  springboot/src/main/kotlin/com/goliath/emojihub/springboot/model/User.kt
  springboot/src/main/kotlin/com/goliath/emojihub/springboot/service/UserService.kt
  springboot/src/main/kotlin/com/goliath/emojihub/springboot/service/UserServiceImpl.kt
Labels: enhancement

#11 Feat/back jwt token
  springboot/build.gradle.kts
  springboot/src/main/kotlin/com/goliath/emojihub/springboot/domain/user/controller/UserController.kt
  springboot/src/main/kotlin/com/goliath/emojihub/springboot/domain/user/dao/UserDao.kt
  springboot/src/main/kotlin/com/goliath/emojihub/springboot/domain/user/dto/LoginRequest.kt
  springboot/src/main/kotlin/com/goliath/emojihub/springboot/domain/user/dto/SignUpRequest.kt
  springboot/src/main/kotlin/com/goliath/emojihub/springboot/domain/user/dto/UserDto.kt
  springboot/src/main/kotlin/com/goliath/emojihub/springboot/domain/user/model/UserAdapter.kt
  springboot/src/main/kotlin/com/goliath/emojihub/springboot/domain/user/service/UserDetailService.kt
  springboot/src/main/kotlin/com/goliath/emojihub/springboot/domain/user/service/UserService.kt
  springboot/src/main/kotlin/com/goliath/emojihub/springboot/global/auth/AuthProperties.kt
  springboot/src/main/kotlin/com/goliath/emojihub/springboot/global/auth/JwtFilter.kt
  springboot/src/main/kotlin/com/goliath/emojihub/springboot/global/auth/JwtTokenProvider.kt
  springboot/src/main/kotlin/com/goliath/emojihub/springboot/global/common/CustomExceptionHandler.kt
  springboot/src/main/kotlin/com/goliath/emojihub/springboot/global/common/Exceptions.kt
  springboot/src/main/kotlin/com/goliath/emojihub/springboot/global/config/FirebaseConfig.kt
  springboot/src/main/kotlin/com/goliath/emojihub/springboot/global/config/SecurityConfig.kt
  springboot/src/main/kotlin/com/goliath/emojihub/springboot/service/UserService.kt
  springboot/src/main/resources/application.yaml
Labels: enhancement
